CREATE DATABASE IF NOT EXISTS wellness_db;
USE wellness_db;

CREATE TABLE IF NOT EXISTS korisnici (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ime VARCHAR(100),
    email VARCHAR(100) UNIQUE NOT NULL,
    lozinka VARCHAR(255) NOT NULL,
    datum_registracije TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);